# Adaptation Normalization Function
#### The normalization function specifies how a normalized response of a neuron depends on the inputs in the normalization pool

$\gamma = $ overall responsiveness

$\sigma = $ prevents division by $0$, determines how responses saturate with increasing driving input

$n = $ amplifies individual inputs

In [151]:
%matplotlib inline

In [156]:
import numpy as np

gamma = 2.0
sigma = 3.0
n = 2.0 # avg exponent n is btwn 1.0 and 3.5 generally, avg 2 REFS 48-50
m = 1
p = 3

I_list = np.array([20, 4, 16])
#w_list = np.array([(1,2,3), (1,5,4), (7, 8, 9)])
w_list = np.ones((len(I_list), len(I_list)))
#alpha_list = np.array([(1,3,6), (3,1,6), (7, 10, 9)])
alpha_list = np.ones((len(I_list), len(I_list)))

beta = 2.0

# j is index 
def normalize(j, lst):
    num = lst.dot(w_list[j]) + beta
    denom = sigma**n + np.power(alpha_list[j].dot(np.power(lst, m)), p)
    return gamma * float(num) / denom

def normalize_lst(lst):
    return np.array([normalize(i, lst) for i in range(len(lst))])

print(normalize(1, I_list))

0.00131231545564


In [157]:
I1_list = np.apply_along_axis(lambda x: x*2, 0, I_list)
I2_list = np.apply_along_axis(lambda x: x*4, 0, I_list)

print(normalize_lst(I_list))
print(normalize_lst(I1_list))
print(normalize_lst(I2_list))

[ 0.00131232  0.00131232  0.00131232]
[ 0.00032031  0.00032031  0.00032031]
[  7.91013887e-05   7.91013887e-05   7.91013887e-05]


In [159]:
from skimage import data, exposure
from skimage.future import graph
from matplotlib import pyplot as plt

img = data.coffee()
gamma_corrected = exposure.adjust_gamma(img, .5)

fig, ax = plt.subplots(nrows=2, sharex=True, sharey=True, figsize=(6, 8))
ax[1].imshow(img)
ax[0].imshow(gamma_corrected)

for a in ax:
    a.axis('off')

plt.show()



ImportError: No module named PIL